[postgresql]
host=localhost
port=5433
database=calval
user=postgres
password=Codio590

[mongodb]
host=localhost
database=nutrition
collection=nutrition
user=mongo
password=cs590password
port=27017

[neo4j]
host=localhost
database=nutrition2
user=neo4j
password=cs590password
port=7687
